#!/usr/bin/env bash
# e2e_lifecycle.sh — end-to-end integration of the memory write path using the
# ACTUAL scripts (as they'd be deployed), in a throwaway HOME, no GitHub remote.
# Exercises: save_memory (+ secret guard) -> deterministic index build -> delete
# (lock + trash + $REPO guard). Proves the changed pieces work together.
set -uo pipefail
REPO_BIN="$(cd "$(dirname "$0")/../bin" && pwd)"
T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT
CL="$T/.claude"
mkdir -p "$CL"
# Deploy the new versions into the throwaway home exactly like install.sh (flat).
for f in memory_lib.sh save_memory.sh save_memory_content_only.sh delete_memory.sh \
         memory_index_build.py memory_reindex.sh memory_curate_check.sh engram_secrets.py; do
    cp "$REPO_BIN/$f" "$CL/$f"
done
chmod +x "$CL"/*.sh "$CL"/*.py

export HOME="$T"
export CLAUDE_MEMORY_SLUG="-e2e-store"
unset CLAUDE_MEMORY_REPO
MEM="$CL/projects/$CLAUDE_MEMORY_SLUG/memory"

fail=0
ck() { if eval "$2"; then echo "  ok: $1"; else echo "  FAIL: $1"; fail=1; fi; }

echo "[1] save a clean memory"
printf -- '---\nname: project_alpha\ndescription: alpha service on port 8080\nmetadata:\n  type: project\n---\n## Summary\nalpha runs on port 8080 at /home/pagcoin/alpha.py\n' \
  | bash "$CL/save_memory.sh" project_alpha.md "alpha service on port 8080" >/dev/null 2>&1
ck "file written" "[[ -f '$MEM/project_alpha.md' ]]"
ck "index line added" "grep -qF '](project_alpha.md)' '$MEM/MEMORY.md'"

echo "[2] secret guard blocks a memory carrying a live token"
if printf -- '---\nname: project_leak\ndescription: has a token\nmetadata:\n  type: project\n---\napi_key=sk_live_51HxYzAbCdEfGhIjKlMnOp\n' \
  | bash "$CL/save_memory.sh" project_leak.md "has a token" >/dev/null 2>&1; then
    echo "  FAIL: leak save should have been BLOCKED"; fail=1
else
    echo "  ok: leak save blocked"
fi
ck "leaked file NOT written" "[[ ! -f '$MEM/project_leak.md' ]]"

echo "[3] add a few more, then deterministically rebuild the index"
for i in 1 2 3; do
  printf -- "---\nname: reference_r$i\ndescription: ref number $i\nmetadata:\n  type: reference\n---\nbody $i\n" \
    | bash "$CL/save_memory.sh" "reference_r$i.md" "ref number $i" >/dev/null 2>&1
done
bash "$CL/memory_reindex.sh" --rebuild --apply >/dev/null 2>&1
idx_bytes=$(wc -c < "$MEM/MEMORY.md")
ck "index regenerated (has generator marker)" "grep -q 'Generated by memory_index_build.py' '$MEM/MEMORY.md'"
ck "all 4 memories linked or noted" "python3 - <<PY
import re
o=open('$MEM/MEMORY.md').read()
linked=len(set(re.findall(r'\]\(([^)]+\.md)\)',o)))
over=sum(int(m) for m in re.findall(r'\+(\d+) more',o))
import glob,os
disk=[p for p in glob.glob('$MEM/*.md') if not p.endswith('MEMORY.md')]
exit(0 if linked+over==len(disk) else 1)
PY"

echo "[4] delete a memory: trashed, index line stripped, no abort with empty REPO"
bash "$CL/delete_memory.sh" project_alpha.md >/dev/null 2>&1
ck "file removed" "[[ ! -f '$MEM/project_alpha.md' ]]"
ck "trash snapshot exists" "ls '$MEM/.trash/'*project_alpha.md >/dev/null 2>&1"
ck "index line stripped" "! grep -qF '](project_alpha.md)' '$MEM/MEMORY.md'"
ck "sibling retained" "grep -qF '](reference_r1.md)' '$MEM/MEMORY.md'"

echo "[5] harvest-failure nudge surfaces from a failing pipeline.log"
mkdir -p "$CL/logs"
for i in $(seq 1 8); do echo "[harvest] x$i.jsonl: ERROR claude -p failed (exit 1): " >> "$CL/logs/pipeline.log"; done
out=$(bash "$CL/memory_curate_check.sh" 2>&1)
ck "harvest-failure warning shown" "grep -qi 'harvester failing' <<<\"\$out\""

echo
[[ $fail == 0 ]] && echo "E2E PASS" || { echo "E2E FAIL"; exit 1; }
